/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CashierPaymentRouteImport } from './routes/cashier.payment'
import { Route as CashierOrdersRouteImport } from './routes/cashier.orders'
import { Route as CashierNewRouteImport } from './routes/cashier.new'
import { Route as CashierMenuRouteImport } from './routes/cashier.menu'
import { Route as CashierHistoryRouteImport } from './routes/cashier.history'
import { Route as CashierCustomersRouteImport } from './routes/cashier.customers'

const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierPaymentRoute = CashierPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CashierRoute,
} as any)
const CashierOrdersRoute = CashierOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => CashierRoute,
} as any)
const CashierNewRoute = CashierNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CashierRoute,
} as any)
const CashierMenuRoute = CashierMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => CashierRoute,
} as any)
const CashierHistoryRoute = CashierHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CashierRoute,
} as any)
const CashierCustomersRoute = CashierCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => CashierRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cashier': typeof CashierRouteWithChildren
  '/kitchen': typeof KitchenRoute
  '/manager': typeof ManagerRoute
  '/cashier/customers': typeof CashierCustomersRoute
  '/cashier/history': typeof CashierHistoryRoute
  '/cashier/menu': typeof CashierMenuRoute
  '/cashier/new': typeof CashierNewRoute
  '/cashier/orders': typeof CashierOrdersRoute
  '/cashier/payment': typeof CashierPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cashier': typeof CashierRouteWithChildren
  '/kitchen': typeof KitchenRoute
  '/manager': typeof ManagerRoute
  '/cashier/customers': typeof CashierCustomersRoute
  '/cashier/history': typeof CashierHistoryRoute
  '/cashier/menu': typeof CashierMenuRoute
  '/cashier/new': typeof CashierNewRoute
  '/cashier/orders': typeof CashierOrdersRoute
  '/cashier/payment': typeof CashierPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cashier': typeof CashierRouteWithChildren
  '/kitchen': typeof KitchenRoute
  '/manager': typeof ManagerRoute
  '/cashier/customers': typeof CashierCustomersRoute
  '/cashier/history': typeof CashierHistoryRoute
  '/cashier/menu': typeof CashierMenuRoute
  '/cashier/new': typeof CashierNewRoute
  '/cashier/orders': typeof CashierOrdersRoute
  '/cashier/payment': typeof CashierPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cashier'
    | '/kitchen'
    | '/manager'
    | '/cashier/customers'
    | '/cashier/history'
    | '/cashier/menu'
    | '/cashier/new'
    | '/cashier/orders'
    | '/cashier/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cashier'
    | '/kitchen'
    | '/manager'
    | '/cashier/customers'
    | '/cashier/history'
    | '/cashier/menu'
    | '/cashier/new'
    | '/cashier/orders'
    | '/cashier/payment'
  id:
    | '__root__'
    | '/'
    | '/cashier'
    | '/kitchen'
    | '/manager'
    | '/cashier/customers'
    | '/cashier/history'
    | '/cashier/menu'
    | '/cashier/new'
    | '/cashier/orders'
    | '/cashier/payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashierRoute: typeof CashierRouteWithChildren
  KitchenRoute: typeof KitchenRoute
  ManagerRoute: typeof ManagerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier/payment': {
      id: '/cashier/payment'
      path: '/payment'
      fullPath: '/cashier/payment'
      preLoaderRoute: typeof CashierPaymentRouteImport
      parentRoute: typeof CashierRoute
    }
    '/cashier/orders': {
      id: '/cashier/orders'
      path: '/orders'
      fullPath: '/cashier/orders'
      preLoaderRoute: typeof CashierOrdersRouteImport
      parentRoute: typeof CashierRoute
    }
    '/cashier/new': {
      id: '/cashier/new'
      path: '/new'
      fullPath: '/cashier/new'
      preLoaderRoute: typeof CashierNewRouteImport
      parentRoute: typeof CashierRoute
    }
    '/cashier/menu': {
      id: '/cashier/menu'
      path: '/menu'
      fullPath: '/cashier/menu'
      preLoaderRoute: typeof CashierMenuRouteImport
      parentRoute: typeof CashierRoute
    }
    '/cashier/history': {
      id: '/cashier/history'
      path: '/history'
      fullPath: '/cashier/history'
      preLoaderRoute: typeof CashierHistoryRouteImport
      parentRoute: typeof CashierRoute
    }
    '/cashier/customers': {
      id: '/cashier/customers'
      path: '/customers'
      fullPath: '/cashier/customers'
      preLoaderRoute: typeof CashierCustomersRouteImport
      parentRoute: typeof CashierRoute
    }
  }
}

interface CashierRouteChildren {
  CashierCustomersRoute: typeof CashierCustomersRoute
  CashierHistoryRoute: typeof CashierHistoryRoute
  CashierMenuRoute: typeof CashierMenuRoute
  CashierNewRoute: typeof CashierNewRoute
  CashierOrdersRoute: typeof CashierOrdersRoute
  CashierPaymentRoute: typeof CashierPaymentRoute
}

const CashierRouteChildren: CashierRouteChildren = {
  CashierCustomersRoute: CashierCustomersRoute,
  CashierHistoryRoute: CashierHistoryRoute,
  CashierMenuRoute: CashierMenuRoute,
  CashierNewRoute: CashierNewRoute,
  CashierOrdersRoute: CashierOrdersRoute,
  CashierPaymentRoute: CashierPaymentRoute,
}

const CashierRouteWithChildren =
  CashierRoute._addFileChildren(CashierRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashierRoute: CashierRouteWithChildren,
  KitchenRoute: KitchenRoute,
  ManagerRoute: ManagerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
